export type MediaItem =
  | { type: 'image'; src: string; alt: string; caption?: string }
  | { type: 'video'; src: string; title: string };

export type ContentBlock = { type: 'text'; html: string } | { type: 'divider'; items: MediaItem[] };

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// Bodies are generated by the migration script with a small, known inline
// vocabulary (**bold**, [text](url), literal newlines standing in for <br>),
// so a minimal renderer is enough — no need for a full markdown engine.
function renderInline(block: string): string {
  const paragraphs = block.split(/\n{2,}/).map((p) => {
    let s = escapeHtml(p.trim());
    s = s.replace(/\[([^\]]*)\]\(([^)]+)\)/g, (_m, text, href) => `<a href="${href}" target="_blank" rel="noreferrer noopener">${text}</a>`);
    s = s.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    s = s.split('\n').join('<br>');
    return `<p>${s}</p>`;
  });
  return paragraphs.join('\n');
}

const IMAGE_RE = /^!\[([^\]]*)\]\(([^)]+)\)(?:\n\*(.+)\*)?$/s;
const VIDEO_RE = /^<iframe\s+src="([^"]+)"\s+title="([^"]*)"/;

// Resolves design.md's open question: a stray empty <p></p> from the WordPress
// scrape is dropped as noise during HTML->markdown conversion (see convert.js),
// never reaches this parser, and therefore never breaks a media run. A
// deliberate pacing break is the only thing that produces a bare (0-item)
// divider, via an explicit `---` block.
export function parseContentBlocks(rawBody: string | undefined): ContentBlock[] {
  if (!rawBody || !rawBody.trim()) return [];

  const rawBlocks = rawBody
    .trim()
    .split(/\n{2,}/)
    .map((b) => b.trim())
    .filter(Boolean);

  type Node = { kind: 'text'; html: string } | { kind: 'media'; item: MediaItem } | { kind: 'break' };
  const nodes: Node[] = [];

  for (const block of rawBlocks) {
    if (block === '---') {
      nodes.push({ kind: 'break' });
      continue;
    }
    const imgMatch = block.match(IMAGE_RE);
    if (imgMatch) {
      nodes.push({
        kind: 'media',
        item: { type: 'image', alt: imgMatch[1] ?? '', src: imgMatch[2], caption: imgMatch[3] },
      });
      continue;
    }
    const videoMatch = block.match(VIDEO_RE);
    if (videoMatch) {
      nodes.push({ kind: 'media', item: { type: 'video', src: videoMatch[1], title: videoMatch[2] } });
      continue;
    }
    nodes.push({ kind: 'text', html: renderInline(block) });
  }

  const result: ContentBlock[] = [];
  let i = 0;
  while (i < nodes.length) {
    const n = nodes[i];
    if (n.kind === 'text') {
      result.push({ type: 'text', html: n.html });
      i++;
      continue;
    }
    if (n.kind === 'break') {
      result.push({ type: 'divider', items: [] });
      i++;
      continue;
    }
    const items: MediaItem[] = [];
    while (i < nodes.length && nodes[i].kind === 'media') {
      items.push((nodes[i] as { kind: 'media'; item: MediaItem }).item);
      i++;
    }
    result.push({ type: 'divider', items });
  }

  return result;
}
